### ISSUE TITLE
Misleading information in Enabling module of Quickstart guide

### ISSUE THREAD

**Issue by unreturned** [deckhouse/csi-nfs#16]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v0.1.3

### Expected Behavior

Quick start guide passed without any questions

### Actual Behavior

We try to do step
```
Wait for the module to become Ready.
kubectl get mc csi-nfs -w
```

and this step can not be finished by instruction because we will never see `Ready` for reason that we does not have field for this.

```
~ $ kubectl get mc csi-nfs -w
NAME      ENABLED   VERSION   AGE   MESSAGE
csi-nfs   true      1         5s
```

Maybe we need to inspect pods for running status in namespace `d8-csi-nfs`?

**Comment by duckhawk** [comment]
Thank you for information, fixed
